server:
  port: 8084


spring:
  cloud:
    gateway:
      routes:
        - id: UserServices
          uri: lb://USERSERVICES
          predicates:
            - Path=/user/**


        - id: HotelService
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotel/**

        - id: RatingServices
          uri: lb://RATINGSERVICES
          predicates:
            - Path=/rating/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-service-url-poll-interval-seconds:
      defaultZone: http://localhost:8761/eureka


#//OKTA configuration for apiGateway
okta:
  oauth2:
    issuer: https://dev-77405221.okta.com/oauth2/default
    audience: api://default
    client-id: 0oah13one27FS5Sk05d7
    client-secret: vxc6oXzLSN5OBuYZ1Zk89eLGnc6Cay2rk_5MnZRg3c-pSiIbuT-v3e2JtMQfkUB0
    scopes: email, profile,openid,offline_access
