server:
  port: 8081
spring:
  datasource:
    url : jdbc:mysql://localhost/microservices
    password : mysql
    username : root
    driver-class-name : com.mysql.cj.jdbc.Driver

#Spring security configration

oauth2:
  resourceserver:
    jwt:
      issuer-uri: https://dev-77405221.okta.com/oauth2/default

#Client configuration
  client:
    registration:
      my-internal-client:
        provider: okta
        authorization-grant-type: client-credential
        scope: internal
        client-id: 0oah13one27FS5Sk05d7
        client-secret: vxc6oXzLSN5OBuYZ1Zk89eLGnc6Cay2rk_5MnZRg3c-pSiIbuT-v3e2JtMQfkUB0

    provider:
      okta:
        issuer-uri: https://dev-77405221.okta.com/oauth2/default



  jpa:
    hibernate:
      ddl-auto : update
    show-sql : true


  config:
    import: configserver:http://localhost:8085

#  profiles:
#    active: prod -> this is used to activate profiles

#    instead of below configuration we are getting configuration from config server above line

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    eureka-service-url-poll-interval-seconds:
#      defaultZone: http://localhost:8761/eureka


#Actutor configuration

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Resilience4J configuration

resilience4j:
  circuitbreaker:
    instance:
      ratingHotelBreaker:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 6s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s

#OKTA configuration

okta:
  oauth2:
    issuer: dev-77405221.okta.com
    audience: api://default









